import { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import axios from "axios";
import { motion } from "framer-motion";
import { Flag, CheckCircle, AlertTriangle } from "lucide-react";

import { requestInterceptor, responseInterceptor, responseErrorInterceptor } from "../../../utils/APIs/interceptors";
import { ERPPageHeader } from "../../erp/shared/ERPPageHeader";
import { ERPLoadingSkeleton } from "../../erp/shared/ERPLoadingSkeleton";
import { ERPEmptyState } from "../../erp/shared/ERPEmptyState";

const api = axios.create({ baseURL: "/api" });
api.interceptors.request.use(requestInterceptor);
api.interceptors.response.use(responseInterceptor, responseErrorInterceptor);

export function FlagsPage() {
  const { user } = useSelector((s) => s.auth);
  const workspaceId = user?.active_workspace_id || 1;
  const [flags, setFlags] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchFlags = async () => {
      setLoading(true);
      try {
        const res = await api.get(`/workspaces/${workspaceId}/flags`, { params: { status: "pending" } });
        setFlags(res.data.flags || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchFlags();
  }, [workspaceId]);

  const resolveFlag = async (flagId) => {
    try {
      await api.post(`/workspaces/${workspaceId}/flags/${flagId}/resolve`);
      setFlags(flags.filter(f => f.id !== flagId));
    } catch (err) {
      alert("Failed to resolve flag");
    }
  };

  if (loading) return <div className="min-h-screen bg-[#0a0a0b]"><ERPLoadingSkeleton /></div>;

  return (
    <div className="min-h-screen bg-[#0a0a0b] text-white overflow-x-hidden">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <ERPPageHeader
          icon={<Flag size={20} />}
          title="Suspicious Flags"
          description="Review and resolve flags generated by anomalous activity."
          breadcrumbs={[{ label: "ERP" }, { label: "Flags" }]}
        />

        <div className="mt-6 bg-[#111115] border border-white/5 rounded-3xl overflow-hidden">
          <div className="p-6 border-b border-white/5 flex items-center justify-between bg-rose-500/5">
            <h3 className="text-base font-bold text-white flex items-center gap-2"><AlertTriangle size={18} className="text-rose-500" /> Pending Flags</h3>
          </div>
          {flags.length === 0 ? (
            <ERPEmptyState icon={<CheckCircle size={24} />} title="No pending flags" sub="There are no suspicious flags awaiting your review." />
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="text-left text-[10px] font-bold uppercase tracking-widest text-zinc-500 bg-black/20">
                  <tr>
                    <th className="px-6 py-4">ID</th>
                    <th className="px-6 py-4">Reason</th>
                    <th className="px-6 py-4">Reported</th>
                    <th className="px-6 py-4 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {flags.map((flag) => (
                    <motion.tr whileHover={{ backgroundColor: "rgba(255,255,255,0.02)" }} key={flag.id} className="transition-colors">
                      <td className="px-6 py-4 font-bold text-zinc-500">#{flag.id}</td>
                      <td className="px-6 py-4 font-semibold text-white">{flag.reason}</td>
                      <td className="px-6 py-4 text-xs font-bold text-zinc-500">{new Date(flag.created_at).toLocaleDateString()}</td>
                      <td className="px-6 py-4 text-right">
                        <button onClick={() => resolveFlag(flag.id)} className="bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-colors flex items-center gap-2 ml-auto">
                          <CheckCircle size={14} /> Resolve
                        </button>
                      </td>
                    </motion.tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}