import { useState, useEffect, useCallback } from "react";
import { useSelector } from "react-redux";
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import { AlertTriangle, CheckCircle, Clock, ShieldAlert, X } from "lucide-react";

import { requestInterceptor, responseInterceptor, responseErrorInterceptor } from "../../../utils/APIs/interceptors";
import { ERPPageHeader } from "../../erp/shared/ERPPageHeader";
import { ERPLoadingSkeleton } from "../../erp/shared/ERPLoadingSkeleton";
import { ERPBannerManager } from "../../erp/shared/ERPBanner";
import { ERPEmptyState } from "../../erp/shared/ERPEmptyState";

const api = axios.create({ baseURL: "/api" });
api.interceptors.request.use(requestInterceptor);
api.interceptors.response.use(responseInterceptor, responseErrorInterceptor);

export function WarningActionsPage() {
  const { user } = useSelector((s) => s.auth);
  const workspaceId = user?.active_workspace_id || 1;
  const [warnings, setWarnings] = useState([]);
  const [loading, setLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(null);
  const [error, setError] = useState(null);

  const loadWarnings = useCallback(async () => {
    if (!workspaceId) return;
    setLoading(true);
    try {
      const res = await api.get("/warnings", { params: { workspace_id: workspaceId } });
      setWarnings(res.data?.data?.warnings || res.data?.data?.items || []);
      setError(null);
    } catch (err) {
      setError("Failed to load warnings");
    } finally {
      setLoading(false);
    }
  }, [workspaceId]);

  useEffect(() => { loadWarnings(); }, [loadWarnings]);

  const resolveWarning = async (id, note = "") => {
    setActionLoading(id);
    try {
      await api.post(`/warnings/${id}/resolve`, { resolution_note: note });
      loadWarnings();
    } catch (err) {
      setError("Failed to resolve warning");
    } finally {
      setActionLoading(null);
    }
  };

  if (loading) return <div className="min-h-screen bg-[#0a0a0b]"><ERPLoadingSkeleton /></div>;

  return (
    <div className="min-h-screen bg-[#0a0a0b] text-white overflow-x-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <ERPPageHeader
          icon={<ShieldAlert size={20} />}
          title="Warning Actions"
          description="Manage and resolve warnings generated by the system."
          breadcrumbs={[{ label: "ERP" }, { label: "Warnings" }]}
        />

        {error && <ERPBannerManager error={error} onDismissError={() => setError(null)} />}

        {warnings.length === 0 ? (
          <ERPEmptyState icon={<CheckCircle size={24} />} title="No pending warnings" sub="Your workspace is operating smoothly with no unresolved warnings." />
        ) : (
          <div className="space-y-4 mt-6">
            <AnimatePresence>
              {warnings.map((w, i) => (
                <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95 }} transition={{ delay: i * 0.05 }} key={w.id}>
                  <WarningCard warning={w} onResolve={resolveWarning} loading={actionLoading === w.id} />
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}
      </div>
    </div>
  );
}

function WarningCard({ warning, onResolve, loading }) {
  const [showModal, setShowModal] = useState(false);
  const typeLabel = warning.type?.replace(/_/g, " ").toUpperCase() || "WARNING";
  
  const handleResolve = (note) => {
    onResolve(warning.id, note);
    setShowModal(false);
  };

  const severityColor = warning.severity === "HIGH" ? "text-red-400 bg-red-500/10 border-red-500/20" : warning.severity === "MEDIUM" ? "text-amber-400 bg-amber-500/10 border-amber-500/20" : "text-zinc-400 bg-zinc-500/10 border-zinc-500/20";

  return (
    <div className="bg-[#111115] border border-white/5 rounded-2xl p-6 transition-all hover:border-white/10">
      <div className="flex flex-col sm:flex-row justify-between items-start gap-4 mb-4">
        <div className="flex flex-wrap items-center gap-3">
          <span className="bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest">{typeLabel}</span>
          <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest border ${severityColor}`}>{warning.severity || "MEDIUM"}</span>
        </div>
        <div className="flex items-center gap-4 text-[10px] font-bold uppercase tracking-widest text-zinc-500">
          <span className="flex items-center gap-1"><Clock size={12} /> {new Date(warning.created_at).toLocaleDateString()}</span>
          {warning.reference_date && <span className="flex items-center gap-1 text-amber-500"><AlertTriangle size={12} /> Due: {warning.reference_date}</span>}
        </div>
      </div>
      
      <p className="text-sm font-semibold text-white mb-6 leading-relaxed bg-black/20 p-4 rounded-xl border border-white/5">{warning.message}</p>
      
      <div className="flex items-center justify-between">
        {!warning.is_resolved ? (
          <button onClick={() => setShowModal(true)} disabled={loading} className="bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-2.5 rounded-xl text-xs font-bold uppercase tracking-widest transition-colors disabled:opacity-50 flex items-center gap-2">
            {loading ? <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> : <CheckCircle size={14} />} {loading ? "Resolving..." : "Resolve"}
          </button>
        ) : (
          <div className="text-[10px] font-bold uppercase tracking-widest text-emerald-500 bg-emerald-500/10 px-4 py-2 rounded-xl flex items-center gap-2">
            <CheckCircle size={14} /> Resolved on {new Date(warning.resolved_at).toLocaleString()}
          </div>
        )}
      </div>

      <AnimatePresence>
        {showModal && <ResolveModal onClose={() => setShowModal(false)} onConfirm={handleResolve} />}
      </AnimatePresence>
    </div>
  );
}

function ResolveModal({ onClose, onConfirm }) {
  const [note, setNote] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async () => {
    setSubmitting(true);
    await onConfirm(note);
    setSubmitting(false);
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.95 }} className="bg-[#111115] border border-white/10 rounded-3xl p-8 w-full max-w-md shadow-2xl">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-lg font-bold text-white flex items-center gap-2"><CheckCircle size={20} className="text-indigo-400" /> Resolve Warning</h3>
          <button onClick={onClose} className="p-2 text-zinc-500 hover:text-white hover:bg-white/5 rounded-xl transition-colors"><X size={16} /></button>
        </div>
        <textarea
          className="w-full bg-[#1a1a20] border border-white/5 rounded-xl p-4 text-sm font-semibold text-white placeholder-zinc-500 focus:outline-none focus:border-indigo-500/50 transition-colors mb-8 resize-none"
          placeholder="Optional resolution note..."
          value={note}
          onChange={(e) => setNote(e.target.value)}
          rows={4}
        />
        <div className="flex gap-3 justify-end">
          <button onClick={onClose} className="bg-transparent hover:bg-white/5 text-white px-6 py-2.5 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-colors">Cancel</button>
          <button onClick={handleSubmit} disabled={submitting} className="bg-emerald-600 hover:bg-emerald-500 text-white px-6 py-2.5 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-colors disabled:opacity-50">
            {submitting ? "Resolving..." : "Confirm"}
          </button>
        </div>
      </motion.div>
    </div>
  );
}