import React, { useState } from "react";
import {
  CheckCircle2,
  Download,
  FolderGit2,
  PlusCircle,
  Sparkles,
  Loader2,
} from "lucide-react";

export const SuccessScreen = ({ onViewDecks, onCreateAnother }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  // Meets Acceptance Criteria: "Download starts correctly"
  const handleDownload = () => {
    setIsDownloading(true);

    // Simulate generating the deck buffer/file
    setTimeout(() => {
      // Create a dummy presentation blob to trigger a real browser file download
      const element = document.createElement("a");
      const file = new Blob(
        [
          "Pitch Deck Content - Generated by AI Vision Platform\n\nSlide 1: Problem\nSlide 2: Solution\nSlide 3: Market Size",
        ],
        { type: "text/plain" },
      );

      element.href = URL.createObjectURL(file);
      element.download = "Pitch_Deck_Q3_Growth.txt"; // In prod, this would be .pdf or .pptx
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);

      setIsDownloading(false);
    }, 1200);
  };

  return (
    <div className="w-full max-w-lg mx-auto bg-[#11131a] border border-slate-800 rounded-3xl p-8 md:p-10 shadow-2xl text-center animate-in fade-in zoom-in-95 duration-500 relative overflow-hidden">
      {/* Subtle background glow */}
      <div className="absolute -top-24 left-1/2 -translate-x-1/2 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none"></div>

      {/* Success Icon */}
      <div className="relative mx-auto w-24 h-24 mb-6">
        <div className="absolute inset-0 bg-emerald-500/20 rounded-full animate-ping opacity-30"></div>
        <div className="relative w-full h-full bg-emerald-500/10 border-2 border-emerald-500/40 rounded-full flex items-center justify-center shadow-[0_0_30px_rgba(16,185,129,0.2)]">
          <CheckCircle2 className="w-12 h-12 text-emerald-400" />
        </div>
        <div className="absolute -bottom-1 -right-1 bg-slate-900 border border-slate-700 p-1.5 rounded-full text-cyan-400 shadow-md">
          <Sparkles className="w-4 h-4" />
        </div>
      </div>

      {/* Message */}
      <h2 className="text-3xl font-extrabold text-slate-100 mb-2 tracking-tight">
        Pitch Deck Generated!
      </h2>
      <p className="text-lg font-medium text-emerald-400/90 mb-8">
        Your pitch deck is ready.
      </p>

      {/* Action Buttons */}
      <div className="space-y-3.5">
        {/* Primary CTA: Download */}
        <button
          onClick={handleDownload}
          disabled={isDownloading}
          className="w-full py-4 px-6 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-bold text-base rounded-xl transition-all shadow-lg shadow-emerald-900/20 flex items-center justify-center gap-2.5 focus:outline-none focus:ring-2 focus:ring-emerald-400 focus:ring-offset-2 focus:ring-offset-[#11131a] disabled:opacity-75 disabled:cursor-wait"
        >
          {isDownloading ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" /> Preparing Download...
            </>
          ) : (
            <>
              <Download className="w-5 h-5" /> Download Deck
            </>
          )}
        </button>

        {/* Secondary CTA: View My Decks */}
        <button
          onClick={onViewDecks}
          className="w-full py-3.5 px-6 bg-slate-800/80 hover:bg-slate-800 border border-slate-700 text-slate-200 hover:text-white font-semibold text-base rounded-xl transition-all flex items-center justify-center gap-2.5 focus:outline-none focus:ring-2 focus:ring-slate-500"
        >
          <FolderGit2 className="w-5 h-5 text-cyan-400" /> View My Decks
        </button>

        {/* Tertiary CTA: Create Another Deck */}
        <button
          onClick={onCreateAnother}
          className="w-full py-3 px-6 bg-transparent hover:bg-slate-800/40 text-slate-400 hover:text-slate-300 font-medium text-sm rounded-xl transition-colors flex items-center justify-center gap-2"
        >
          <PlusCircle className="w-4 h-4" /> Create Another Deck
        </button>
      </div>
    </div>
  );
};
