import {
  CheckCircle,
  Save,
  MessageSquareHeart,
  Rocket,
  Users,
  ClipboardList,
  FileTerminal,
  Hammer,
  TrendingUp,
  Settings,
  BarChart3,
  BarChart2,
  FolderOpen,
  Bell,
  HardDrive,
  Presentation,
  DollarSign,
  ShoppingCart,
  ShoppingBag,
  Coins,
  Trophy,
  Wallet,
  GraduationCap,
  Search,
  Star,
  Mail,
  Building2,
  CalendarClock,
  FileStack,
  Activity,
  ShieldCheck,
  ChevronDown,
  Video,
} from "lucide-react";
import {
  aiTools,
  dashboardLink,
  ideation,
  socialSection,
  toolsSection,
  erpSection,
  filterERPModules,
  sfDriveSection,
  sfMeetSection,
  learningSection,
  mentorshipSection,
  walletSection
} from "../sidebarCommons";
import { FcInvite } from "react-icons/fc";

export function createBuilderLinks(unreadMessagesCount, userRoles = [], setActiveRole = () => { }, activeRole = 'builder') {
  const erp = { ...erpSection(11), subItems: filterERPModules(erpSection(11).subItems, activeRole, userRoles) };
  return [
    dashboardLink(userRoles, setActiveRole),
    {
      id: 2,
      icon: <Rocket size={22} />,
      href: "/discover-startups",
      label: "Discover Startups",
      subItems: [
        {
          id: "discover-startups",
          href: "/discover-startups",
          label: "Discover Startups",
          icon: <Rocket size={18} />,
        },
        {
          id: "matching-startups",
          href: "/builder/matching-startups",
          label: "Matching Startups",
          icon: <Star size={18} />,
        },
        {
          id: "saved-startups",
          href: "/saved-startups",
          label: "Saved Startups",
          icon: <Save size={18} />,
        },
      ],
    },
    ideation(3, "builder"),
    {
      id: 5,
      icon: <Hammer size={22} />,
      href: "/builder/my-startups",
      label: "My Startups",
      subItems: [
        {
          id: "my-startups",
          href: "/builder/my-startups",
          label: "My Startups",
          icon: <Hammer size={18} />,
        },
        {
          id: "my-applications",
          href: "/builder/my-applications",
          label: "My Applications",
          icon: <CheckCircle size={18} />,
        },
        {
          id: "my-work",
          href: "/builder/my-work",
          label: "My Work",
          icon: <ClipboardList size={18} />,
        },
        {
          id: "my-invitations",
          href: "/invitations",
          label: "My Invitations",
          icon: <FcInvite size={18} />,
        },
      ],
    },
    socialSection(7),
    aiTools(8, "builder"),
    toolsSection(9),
    { id: "section-grow", sectionLabel: "Grow", isSection: true },
    // Builders receive mentorship; they don't run a mentor dashboard, so that
    // entry has been dropped from this role's navigation.
    mentorshipSection(6, "builder"),
    learningSection(14, "builder"),
    { id: "section-earn", sectionLabel: "Earn", isSection: true },
    walletSection(10),
    { id: "section-workspace", sectionLabel: "Workspace", isSection: true },
    erp,
    sfDriveSection(12),
    sfMeetSection(13),
  ];
}