export const mockUsers = [
  {
    id: 1,
    first_name: "Sarah",
    last_name: "Chen",
    title: "Full Stack Developer",
    company: "TechCorp",
    bio: "Passionate about building scalable web applications and mentoring junior developers.",
    location: "San Francisco, CA",
    expertise: "React, Node.js",
    skills: ["JavaScript", "React", "Node.js", "PostgreSQL", "AWS"],
    followers: 245,
    contributions: 87,
    avatar_url: null,
  },
  {
    id: 2,
    first_name: "Marcus",
    last_name: "Johnson",
    title: "DevOps Engineer",
    company: "CloudScale",
    bio: "Infrastructure automation and deployment optimization specialist.",
    location: "Austin, TX",
    expertise: "Kubernetes, Docker",
    skills: ["Docker", "Kubernetes", "Terraform", "Python", "AWS"],
    followers: 189,
    contributions: 65,
    avatar_url: null,
  },
  {
    id: 3,
    first_name: "Elena",
    last_name: "Rodriguez",
    title: "UX/UI Designer",
    company: "DesignStudio",
    bio: "Creating beautiful and intuitive user experiences.",
    location: "Barcelona, Spain",
    expertise: "Figma, Design Systems",
    skills: ["Figma", "Prototyping", "User Research", "CSS"],
    followers: 312,
    contributions: 102,
    avatar_url: null,
  },
  {
    id: 4,
    first_name: "David",
    last_name: "Kim",
    title: "Mobile Developer",
    company: "AppWorks",
    bio: "Building native iOS and Android applications.",
    location: "Seoul, South Korea",
    expertise: "Swift, Kotlin",
    skills: ["Swift", "Kotlin", "React Native", "Firebase"],
    followers: 156,
    contributions: 48,
    avatar_url: null,
  },
];