name: Deploy Frontend Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: aws s3 sync dist s3://sf-collab-pre-deploy --delete --exclude "uploads/*"

      - name: Clear CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E1QYCFGNGX3SX4 --paths "/*"
